#!/bin/bash
set -e

# Raspberry Pi dnsmasq script
# 
# Usage: $ sudo ./raspberrypi_dnsmasq
#
# Net install:
#   $ curl https://raw.github.com/stephendotexe/raspberrypi/master/roles/dnsmasq_server | sudo sh

# Must be run as root
if [[ `whoami` != "root" ]]
then
  echo "This install must be run as root or with sudo."
  exit
fi

apt-get install -y dnsmasq
cat - > /etc/dnsmasq.d/pimasq.conf <<DNSMASQCONF
# Dnsmasq.conf for raspberry pi    

# Set up your local domain here    
domain=raspberry.local    
resolv-file=/etc/resolv.dnsmasq  
min-port=4096   
# opendns family shield servers
server=208.67.222.123
server=208.67.220.123
      
# Max cache size dnsmasq can give us, and we want all of it!    
cache-size=10000    
      
# Below are settings for dhcp. Comment them out if you dont want    
# dnsmasq to serve up dhcpd requests.    
dhcp-range=192.168.29.10,192.168.29.99,255.255.255.0,1440m    
dhcp-option=3,192.168.29.1    
dhcp-authoritative

DNSMASQCONF

service dnsmasq restart

echo 'Installation complete. Enjoy!'